# Generated by Django 5.0.7 on 2024-09-03 10:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
