# Generated by Django 5.0.7 on 2024-09-12 10:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_risk_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
